### ISSUE TITLE
Example for implementing the hook

### ISSUE THREAD

**Issue by ACPK** [CanopyFA/quovo-ruby#9]
How would I implement the hook mentioned below:

    Quovo.hook do |path, method, params, status_code, response, elapsed_time, scope|
    end

**Comment by gorkunov** [comment]
You can find example here: https://github.com/CanopyFA/quovo-ruby/blob/master/lib/quovo.rb#L61

**Comment by ACPK** [comment]
@gorkunov So this goes in the initializer?

**Comment by gorkunov** [comment]
right!
